names=(BA BB BC BD BE BF BG BH BI BJ CA CB CC CD CE CF CG CH CI CJ DA DB DC DD DE DF DG DH DI DJ  
 EA EB EC ED EE EF EG EH EI EJ FA FB FC FD FE FF FG FH FI FJ GA GB GC GD GE GF GG GH GI GJ 
 HA HB HC HD HE HF HG HH HI HJ IA IB IC ID IF IG IH II IJ JA JB JC JD JE JF JG JH JI JJ)

i=0
for name in ????*.smi
do
mv  $name  ${names[i]}'.smi'
((i++))

done
